[tools]
"aqua:go-task/task" = "latest"
uv = "latest"
bun = "latest"
gh = "latest"
prek = "latest"
usage = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[tools."github:can1357/oh-my-pi"]
version = "latest"
minimum_release_age = "0d"

[settings.npm]
package_manager = "bun"
