[tools]
"aqua:go-task/task" = "latest"
bun = "latest"
gh = "latest"
"github:can1357/oh-my-pi" = "latest"
go = "latest"
hugo = "latest"
java = "21"
maven = "latest"
prek = "latest"
rust = {version = "latest", components = "rust-analyzer"}
usage = "latest"

[settings]

[settings.cargo]
binstall = true

[settings.npm]
package_manager = "bun"
