[[language]]
name = "python"
language-servers = [ "ty", "ruff" ]
auto-format = true
formatter = { command = "bash", args = ["-c", "ruff check --select I001 --fix - | ruff format -"] }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "markdown"
language-servers = [ "markdown-oxide" ]

[[language]]
name = "go"
language-servers = [ "gopls" ]

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true
